[package]
name = "eth2-libp2p"
version = "0.2.0"
authors = ["Age Manning <Age@AgeManning.com>"]
edition = "2018"

[dependencies]
hex = "0.3"
# rust-libp2p is presently being sourced from a Sigma Prime fork of the
# `libp2p/rust-libp2p` repository.
libp2p =  { git = "https://github.com/pawanjay176/rust-libp2p", rev = "28ea1846628721f7fede4e3acb7e913b3ae6f7b7" }
types = { path =  "../../eth2/types" }
hashmap_delay = { path = "../../eth2/utils/hashmap_delay" }
eth2_ssz_types = { path =  "../../eth2/utils/ssz_types" }
serde = { version = "1.0.102", features = ["derive"] }
serde_derive = "1.0.102"
eth2_ssz = "0.1.2"
eth2_ssz_derive = "0.1.0"
slog = { version = "2.5.2", features = ["max_level_trace"] }
version = { path = "../version" }
tokio = {version = "0.2", features = ["time"] }
futures = "0.3"
error-chain = "0.12.1"
dirs = "2.0.2"
fnv = "1.0.6"
unsigned-varint = "0.3.3"
lazy_static = "1.4.0"
lighthouse_metrics = { path = "../../eth2/utils/lighthouse_metrics" }
smallvec = "1.0.0"
lru = "0.4.3"
parking_lot = "0.9.0"
sha2 = "0.8.0"
base64 = "0.11.0"
snap = "1"
void = "1.0.2"
tokio-util = {version = "0.3.1", features = ["codec"]}

[dev-dependencies]
slog-stdlog = "4.0.0"
slog-term = "2.4.2"
slog-async = "2.3.0"
tempdir = "0.3"
